version: "3"

services:
  django:
    image: django_stripe
    build: django_stripe
    env_file: .env
    ports:
    - "${APP_PORT}:${APP_PORT}"
    volumes:
      - static_volume:/code/static/
    environment:
      - "DOMAIN=${DOMAIN}"
  nginx:
    image: django_nginx
    build: nginx
    network_mode: host
    volumes:
      - static_volume:/code/static/

volumes:
     static_volume:
